### PR TITLE
Add Eberron Rising from the Last war as an official source and creatu…

### PR DESCRIPTION
**Pull request by gwillad**
…res from chapter 6 (friends and foes)

### CODE REVIEW

**Comment by gwillad** [comment]
@V13Axel here's that PR (fantasycalendar/scaled-encounter #7) reopened for the correct repo

**Comment by V13Axel** [comment]
Hey there, sorry for the delay on this - We'll be giving this a thorough look soon!

**Comment by gwillad** [comment]
@V13Axel pinging on this - starting up my campaign again on here soon :)

**Comment by V13Axel** [comment]
Hey, sorry - Things have been ultra-hectic on our end for the last few months, but one of us will try to give this a look sometime this week

**Comment by Haxxer** [comment]
Apologies for the long wait! Thank you for the contribution! :)

**Comment by gwillad** [comment]
Happy to contribute! Thanks for merging :)

**Pull request merged**
